### PR TITLE
Update to use Avalonia 0.9

### PR DESCRIPTION
**Pull request by worldbeater**
Folks have been working on oxyplot support for Avalonia in a separate repo. But wouldn't it be wonderful if we consolidated our efforts and got an update to `OxyPlot.Avalonia` package in NuGet? This PR brings the most recent changes from https://github.com/AvaloniaUI/oxyplot-avalonia/pull/9, this should make `OxyPlot.Avalonia` package compatible with Avalonia 0.9.

### CODE REVIEW

**Comment by objorke** [comment]
Thanks for bringing in the changes!

**Comment by objorke** [comment]
Do you prefer to work in the AvaloniaUI fork, or should we add more team members here?

**Comment by worldbeater** [comment]
@objorke folks from the Avalonia team say, that any option would suite them. Adding more team members here would be convenient as long as [Avalonia devs](https://github.com/orgs/AvaloniaUI/people) have push access to be able to submit fixes and enhancements once a new Avalonia stable version is out (with potential breaking changes). 

Another question is the [NuGet package](https://www.nuget.org/packages/OxyPlot.Avalonia/2.0.0-unstable0956), which hasn't received updates for a long period of time. I know folks tend to use `OxyPlot.Avalonia` via git submodules. Could you please provide the guidance about how to prepare a NuGet package for `OxyPlot.Avalonia`? Tried the following:

```sh
# Ubuntu 18 with .NET Core 3.1 SDK installed.
git clone git@github.com:oxyplot/oxyplot-avalonia.git
cd ./oxyplot-avalonia/Source/OxyPlot.Avalonia
dotnet build -c Release
dotnet pack -c Release
```

And this produced the [following package](https://yadi.sk/d/ASjEwM1XBZBCaw), probably ready to be uploaded to NuGet, feel free to reproduce. Thanks for the help!

**Comment by objorke** [comment]
I have added you to the @oxyplot/avalonia team, you should have "maintainer" permissions now! 
#6 created for the NuGet packages!

**Pull request merged**
