### PR TITLE
Update to 2.1.0

### PR DESCRIPTION
**Pull request by VisualMelon**
TODO:
 - [x] review edge rendering modes in `CanvasRenderContext`
 - [x] check column examples (if any remain)
 - [x] investigate perf (feels pretty poor; may be changes in `CanvasRenderContext`)
 - [x] investigate crashing examples (in `AvaloniaExamples`):
     - [x] `BarSeriesDemo`
     - [x] `HeatMapDemo`
     - [x] all `UserControlDemos` are broken
 - [x] can't pan/zoom `Plot` with default axes (e.g. `Line and Area` example)

There are many changes that will need some time to 'sink in', so I don't think a 2.1.0 release will be viable soon if we want it to be stable, though we should provide a pre-release to get feedback. May be worth releasing a 2.0 version before the update.

### CODE REVIEW

**Comment by BobLd** [comment]
Hi @VisualMelon, thanks a lot for you job on that.

I've used the modifications in your branch to swith to 2.1.0 but it seems that the Legend does not implement `CreateModel()`. I had to comment the `internalModel.Legends.Add(l.CreateModel());` line. Let me know if I did something wrong.

Also, let me know if I can help speeding up the move to 2.1.0

**Comment by VisualMelon** [comment]
@BobLd wow, looks like I forgot to add the `Legend` code in my commits. My local branch was a bit of a mess; I was hoping to have lots of time for 2.1 work, but that hasn't worked out at all.

If you're keen to help, the OP above lists some issues I'd identified, but didn't get around to addressing: any progress on understanding/fixing those would be very welcome, but I'm afraid I really don't have a lot of time at the moment to get stuck into large issues like this.

**Comment by BobLd** [comment]
@VisualMelon, thanks a lot for your prompt feedback, that's great! Will test it shortly.

I'll have a look at the list above and see what I can do. Thanks again!

**Comment by VisualMelon** [comment]
To clarify, the line you removed should be there: hopefully with the `Legend` code in-place it'll be happier.

I can't find any column examples, and I do seem to be able to pan default axes, so not sure what they were about. I think the issue that was really doing my head in was the crash with `BarSeriesDemo` in the `AvaloniaExamples` project (indeed, I still have some lingering break-points on that stuff); I think I concluded that was due to some weirdness in the new `BarSeriesManager`, and couldn't work out how to work around it in Avalonia. I don't recall investigating the other crashes.

Perf does feel terrible; probably best to start by working out when the regression was introduced.

**Comment by BobLd** [comment]
Regarding the `BarSeriesDemo`, the issues I have spotted are:
- Last bar series not rendered when using plot/xaml:
image
image
One (dirty) way to fix that is, in `PlotBase`, to replace the `OnSizeChanged` by the following. Unfortunatly, I could not find a better way.
```csharp
        private void OnSizeChanged(object sender, Size size)
        {
            if (size.Height > 0 && size.Width > 0)
            {
                InvalidatePlot(sender is Plot);
            }
        }
```
- System.InvalidOperationException when clicking on legend in plot/xaml mode. I still need to investigate that. **NB**: I have updated Avalonia to 0.10.11-rc.2.

**Comment by VisualMelon** [comment]
Ah, yes. The issues are all with the XAML stuff, of course...:
 - The Area Series demo has default axes, and those refuse to zoom/pan
 - Legends crash, as you observe

Re. bar series, it seems to be due the differences between `ItemsControl.Items` in Avalonia (which defaults to an empty collection) and `ItemsControl.ItemsSource` in WPF (which defaults to `null`): the empty collection makes `BarSeriesManager` unhappy in the former case, because it expects `ItemsSourceItems` to have been initialised, but it has not. Setting `Items = null` in `Series` seems to stop the crashes (without seeming to break anything else), but doesn't resolve the missing series.

**Comment by VisualMelon** [comment]
Missing series is just a small error in `BarSeriesBase`: the `ValueField` property was only invoking `AppearanceChanged`, not `DataChanged`; line 100 of `BarSeriesBase` should be

    ValueFieldProperty.Changed.AddClassHandler<BarSeriesBase>(DataChanged);

**Comment by BobLd** [comment]
Well spotted, it's fixed in my branch. Thanks for that!

Will try to have a look at the other exception (of course no RC in final package by the way)

**Comment by VisualMelon** [comment]
@BobLd cool; does it work for you without the `Items = null` assignment? Mine still crashes without it. I think this reveals an issue with the core library (it should tolerate an empty series), but consistency with OxyPlot-Contrib is probably a good thing.

**Comment by BobLd** [comment]
@VisualMelon, It runs without crashing and I can see the bar charts.

I did not add `Items = null` in `Series..ctor`, and as far as I can see, it's not here in the version I have (just to make sure we are talking about the same thing):
```csharp
protected Series()
{
    eventListener = new EventListener(OnCollectionChanged);
}
```

Let me know if I misunderstood something

**Comment by VisualMelon** [comment]
@BobLd no, I think you've understood perfectly. I just tested and your code crashes on my machine; I suppose this must be an inconsistency in some non-deterministic behaviour in the Avalonia property engine.

On my machine, without `Items = null` in the `Series` constructor the XAML BarSeries example crashes because `Items` is initially an empty list, and `BarSeriesManager` doesn't like that. Including it in your code resolves the issue for me again.

I think we should include the line with a comment explaining this, because it makes it more consistent with `Wpf-Contrib`. Something like

    // Set Items to null for consistency with WPF behaviour in Oxyplot-Contrib
    // Works around issue with BarSeriesManager throwing on empty Items collection in OxyPlot.Core 2.1
    Items = null;

I should sort out a PR to fix the core side of things.

**Comment by BobLd** [comment]
That's very strange! For the records, I'm running the code on a Windows 10 laptop, and yes - it seems your solution is the only one short term.

I continue working on the performance side of things in my branch using your PR. e.g. I've created `DrawPolygonsByStreamGeometry()` to avoid a lots of `if` statements during drawing and remvoving from the loops code that needs to be run only once

**Comment by VisualMelon** [comment]
`InvalidatePlot` is calling `Plot.UpdateModel`, which calls `SynchronizeAxes` which deletes the default axes, causing the problems with panning/zooming when default axes are used.

Two problems with this:
 1. `InvalidatePlot` probably shouldn't be calling `UpateModel` as implemented in `Plot`: it should not re-build the entire model every time anything happens.
 2. Syncing axes probably shouldn't purge default axes

I'm trying to work out how to resolve the first by referencing `OxyPlot-Contrib` (which doesn't do this), but it's taking a while. This change may have knock-on effects.

The second can probably be resolved by only removing axes that are not listed as default axes. Again, this may have some knock-on effects.

Fixing either should resolve the no-panning problem; the first should definitely be resolved if possible; the second is also present in `OxyPlot-Contrib`.

**Comment by BobLd** [comment]
Update concerning `Items = null`: I've just added the Oxyplot project as a direct reference (not the NuGet) and it indeed throws in `BarSeriesManager` if `Items = null`. It must have thrown silently before. At leaast the behaviour is consistent.

I'm currently working on the Bar series legend exception

**Comment by VisualMelon** [comment]
I think I've resolved that last. It looks like I made a similar set of changes in OxyPlot-Contrib a while back, and I've pretty much just copied those.

@BobLd I've rebased your stuff into my 2.1 branch (corresponding to this PR): I hope you don't mind? This should make it easier for us to discuss details within the confines of the PR.

<hr />

New XAML issues noticed:
 [ ] Setting `Foreground` on `PieSeries` breaks its text, which is otherwise not as expected (grey rather than default of black; see PieDemo)
 [ ] Example for `EllipseAnnotation` crashes
 [ ] Example for `PolylineAnnotation` doesn't show

**Comment by BobLd** [comment]
@VisualMelon, on the contrary, thanks for using my work! Okay I'll check if I still have the legend issue then with your latest update.

Thanks for listing the new issues, will look at that

**Comment by BobLd** [comment]
Re `EllipseAnnotation`, it seems to work on my side: 
image

**Comment by VisualMelon** [comment]
@BobLd sorry, missed your first message. Thanks for checking the `Items = null` crash; makes more sense than my explanation!

> EDIT: Any idea what's the purpose of BeginBatchUpdate() and EndBatchUpdate() in Avalonia?

I don't, but you can always try asking in the Avalonia gitter: the devs and other experienced community members are pretty responsive there: https://gitter.im/AvaloniaUI/Avalonia

> Re EllipseAnnotation, it seems to work on my side:

Sorry, should have been clearer; it's just in the `WpfExamples` project (i.e. where the examples are mostly XAML Plot based, rather than PlotView based), under the `AnnotationDemo` example (third from the top). I'm not aware of any significant outstanding Avalonia-specific issues with the non-XAML stuff at the moment (i.e. everything in the `ExampleBrowser` should be consistent with e.g. WPF)

**Comment by BobLd** [comment]
Re `Example for PolylineAnnotation doesn't show` issue, it seems to be a general issue in the `Example Browser` project:
When you first click on an example within a category, the first click won't update the model. You need to click on another example in the same category for the model to change. Because the `PolylineAnnotation` category has only one example in it, it's not possible to make it change.

As a side not, when you put break points in `MainViewModel`'s `Model` Property and run the update step by step,, it will work nicely
image

**Comment by VisualMelon** [comment]
@BobLd ah, again I meant the XAML `AnnotationDemo` example for `PolyLine` (pictured)
image

None-the-less, thankyou for investigating the weirdness in the `ExampleBrowser`; that issue has always been there, and I vaguely recall thinking it was to do with focus, but I've never really looked into it properly.

The example browser issue should probably be in its own issue if you want to make one, since it is independent of the 2.1 changes.

**Comment by VisualMelon** [comment]
I can't see anything wrong with the UserControl demos now, but they don't look like their pictures (I suppose we should update the pictures? (low priority)). Marking that as resolved in the OP.

I've fixed `EllipseAnnotation` by adding more callbacks; OxyPlot-Contrib doesn't have them, so not sure what that is about.

**Comment by BobLd** [comment]
haha my bad :D And yes, well spotted for the `EllipseAnnotation` the Width/Height were NaN

**Comment by BobLd** [comment]
for the polyliine issue, adding the following seems to do the trick:
`PointsProperty.Changed.AddClassHandler<PolylineAnnotation>(DataChanged);`

**Comment by BobLd** [comment]
Fixed PieSeries color issues, problem was in `ToOxyColor()`

**Comment by VisualMelon** [comment]
@BobLd thanks! (using your fixes over mine)

I'm not sure why the `Foreground` snaps to `Gray` in `PieSeries` when it isn't explicitly, but I don't think that's an issue with the library, so I'm not worried about it for the purpose of this PR.

**Comment by VisualMelon** [comment]
I'm not at this time aware of any remaining serious issues. We might want to do something about #32 before a release, but I think this gets up-to-date with 2.1.

**Comment by BobLd** [comment]
@VisualMelon  My pleasure! I'm working on the performance improvements. I guess the easiest solution would be to always use `DrawPolygon(s)` in order to use `DrawPolygonsByStreamGeometry`.

Also, I think there's an issue in `DrawPolygons()` when `UseStreamGeometry` is not activated. My bad! checking right now

**Comment by BobLd** [comment]
@VisualMelon - Issue in `DrawPolygons()` fixed in my branch. I'll create another PR for the performance improvements

**Comment by VisualMelon** [comment]
@BobLd  good catch, merged.

**Comment by BobLd** [comment]
@VisualMelon - I've added `DrawEllipsesByStreamGeometry` which improve greatly the rendering performance of circle marker, still in https://github.com/BobLd/oxyplot-avalonia/commits/oxy2.1

**Comment by VisualMelon** [comment]
@BobLd fantastic, that is a massive improvement!

Could we change `isDefined` to `isSolid`?

**Comment by BobLd** [comment]
@VisualMelon sure, it's now updated

**Comment by VisualMelon** [comment]
@BobLd do you have any other perf issues you are looking into?

If not, I think this is probably ready for a 2.1.0-Preview1 release to nuget. This will give people a chance to use it and abuse it before we commit to 2.1.0.

I'm going to do some testing to see if there is an issue with plots in docks, as we had issues with Wpf in the main repo.

**Comment by BobLd** [comment]
I'm good for the moment and I'm happy for you to merge and making the preview1 available 💪

**Comment by VisualMelon** [comment]
2.1.0-Preview1 pushed to NuGet.

**Pull request merged**
